### ISSUE TITLE
suggest to upgrade to Preston v0.2.5

### ISSUE THREAD

**Issue by jhpoelen** [matdillen/prestontest#1]
It appears that your diversity archive uses an older version of Preston v0.2.3:

```
$ preston ls | grep Preston | tail -n1
<https://doi.org/10.5281/zenodo.1410543> <http://purl.org/dc/terms/bibliographicCitation> "Jorrit Poelen, Icaro Alzuru, & Michael Elliott. 2019. Preston: a biodiversity dataset tracker (Version 0.2.3) [Software]. Zenodo. http://doi.org/10.5281/zenodo.1410543"@en <urn:uuid:0e837ee8-3387-4f6b-a1ef-b8f3c0692379> .
```

Suggest to upgrade to Preston v0.2.5 . This version has support for traversing GBIF occurrence search api results. Also see https://github.com/bio-guoda/preston/releases .

**Comment by matdillen** [comment]
Thanks, yes that did the trick. I used the default install instructions for preston and those still refer to the older version.

**Comment by jhpoelen** [comment]
@matdillen apologies for the confusion. It turns out that I updated the "quick install" instructions, but not the more extended version of the instructions. Thanks for pointing that out, I've updated the documentation.
